.TH netsck 7 2021-12-27 "API" "Javascript API Manual"

.SH NAME
.B Key
: singleton class

.SH DESCRIPTION
.BR Key
is an
.B singleton
class which provides readable key names.
It is not instantiable.

.SH EXAMPLE

.B var
c = 0;
.br
.br

.B while
( ( c = 
.B wait_key( 33 )
) !=
.B Key.ESC
)
.br
{
.br
    if ( c ==
.B Key.Space
)
.br
        print( "Space is pressed." );
.br
}

.SH CONSTANTS
.TP
.B TAB
.TP
.B RETURN
.TP
.B ESC
.TP
.B Space
.TP
.B Exclam
.TP
.B D0
.TP
.B D1
.TP
.B D2
.TP
.B D3
.TP
.B D4
.TP
.B D5
.TP
.B D6
.TP
.B D7
.TP
.B D8
.TP
.B D9
.TP
.B Colon
.TP
.B SemiColon
.TP
.B Less
.TP
.B Equal
.TP
.B Greater
.TP
.B Question
.TP
.B At
.TP
.B A
.TP
.B B
.TP
.B C
.TP
.B D
.TP
.B E
.TP
.B F
.TP
.B G
.TP
.B H
.TP
.B J
.TP
.B K
.TP
.B L
.TP
.B M
.TP
.B N
.TP
.B O
.TP
.B P
.TP
.B Q
.TP
.B R
.TP
.B S
.TP
.B T
.TP
.B U
.TP
.B V
.TP
.B W
.TP
.B X
.TP
.B Y
.TP
.B Z
.TP
.B Underscore
.TP
.B a
.TP
.B b
.TP
.B c
.TP
.B d
.TP
.B e
.TP
.B f
.TP
.B g
.TP
.B h
.TP
.B j
.TP
.B k
.TP
.B l
.TP
.B m
.TP
.B n
.TP
.B o
.TP
.B p
.TP
.B q
.TP
.B r
.TP
.B s
.TP
.B t
.TP
.B y
.TP
.B v
.TP
.B w
.TP
.B x
.TP
.B y
.TP
.B z
.TP
.B Tilda
.TP
.B Backspace
.br
.br